version: "3.8"
services:
  flask-chatbot-socketio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "12121:5000"
    volumes:
      # setup file or folder
      - /mnt/storage/flask-chatbot-socketio:/app/training_data
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
